name = "cloudflare-poc-web2"
compatibility_date = "2025-12-04"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[build]
command = "pnpm run build"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"